/*
Copyright (c) 2023 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dgpu.asset.mipmap;

import std.stdio;
import std.file;
import std.string;
import std.math;
import std.algorithm;
import std.conv;

import bindbc.wgpu;
import dgpu.core.gpu;
import dgpu.asset.texture;

void generateMipmap(GPU gpu, Texture texture)
{
    WGPUSamplerDescriptor samplerDesc = {
        label: "mip",
        addressModeU: WGPUAddressMode.ClampToEdge,
        addressModeV: WGPUAddressMode.ClampToEdge,
        addressModeW: WGPUAddressMode.ClampToEdge,
        minFilter: WGPUFilterMode.Linear,
        magFilter: WGPUFilterMode.Nearest,
        mipmapFilter: WGPUMipmapFilterMode.Nearest,
        lodMinClamp: 0.0f,
        lodMaxClamp: 1.0f,
        maxAnisotropy: 1
    };
    
    WGPUSampler sampler = wgpuDeviceCreateSampler(gpu.device, &samplerDesc);
    
    WGPUPrimitiveState primitiveStateDesc = {
        topology: WGPUPrimitiveTopology.TriangleStrip,
        stripIndexFormat: WGPUIndexFormat.Uint32,
        frontFace: WGPUFrontFace.CCW,
        cullMode: WGPUCullMode.None
    };
    
    WGPUBlendState blendState = {
        color: {
            srcFactor: WGPUBlendFactor.One,
            dstFactor: WGPUBlendFactor.Zero,
            operation: WGPUBlendOperation.Add
        },
        alpha: {
            srcFactor: WGPUBlendFactor.One,
            dstFactor: WGPUBlendFactor.Zero,
            operation: WGPUBlendOperation.Add
        }
    };
    
    WGPUColorTargetState colorTargetState = {
        format: texture.format,
        blend: &blendState,
        writeMask: WGPUColorWriteMask.All,
    };
    
    WGPUBindGroupLayoutEntry[2] bindGroupLayoutEntries = [
        {
            nextInChain: null,
            binding: 0,
            visibility: WGPUShaderStage.Fragment,
            sampler: {
                nextInChain: null,
                type: WGPUSamplerBindingType.Filtering
            }
        },
        {
            nextInChain: null,
            binding: 1,
            visibility: WGPUShaderStage.Fragment,
            texture: {
                nextInChain: null,
                sampleType: WGPUTextureSampleType.Float,
                viewDimension: WGPUTextureViewDimension.D2,
                multisampled: false
            }
        }
    ];
    
    WGPUBindGroupLayoutDescriptor bindGroupLayoutDescriptor = {
        label: "MipmapBindGroupLayout",
        entries: bindGroupLayoutEntries.ptr,
        entryCount: bindGroupLayoutEntries.length
    };
    WGPUBindGroupLayout bindGroupLayout = wgpuDeviceCreateBindGroupLayout(gpu.device, &bindGroupLayoutDescriptor);
    
    WGPUBindGroupLayout[1] bindGroupLayouts = [ bindGroupLayout ];
    WGPUPipelineLayoutDescriptor pipelineLayoutDesc = {
        bindGroupLayouts: bindGroupLayouts.ptr,
        bindGroupLayoutCount: bindGroupLayouts.length
    };
    
    WGPUPipelineLayout pipelineLayout = wgpuDeviceCreatePipelineLayout(gpu.device, &pipelineLayoutDesc);
    
    const(char)* shaderText = readText("data/shaders/mipmap.wgsl").toStringz;
    WGPUShaderModuleWGSLDescriptor wgslDescriptor = {
        chain: {
            next: null,
            sType: WGPUSType.ShaderModuleWGSLDescriptor
        },
        code: shaderText
    };
    WGPUShaderModuleDescriptor shaderSource = {
        nextInChain: cast(const(WGPUChainedStruct)*)&wgslDescriptor,
        label: toStringz("shader.wgsl")
    };
    WGPUShaderModule shaderModule = wgpuDeviceCreateShaderModule(gpu.device, &shaderSource);
    
    WGPUFragmentState fragmentState = {
        module_: shaderModule,
        entryPoint: "fs_main",
        targetCount: 1,
        targets: &colorTargetState
    };
    
    WGPURenderPipelineDescriptor pipelineDesc = {
        label: "Mipmap pipeline",
        layout: pipelineLayout,
        vertex: {
            module_: shaderModule,
            entryPoint: "vs_main",
            bufferCount: 0,
            buffers: null
        },
        primitive: {
            topology: WGPUPrimitiveTopology.TriangleStrip,
            stripIndexFormat: WGPUIndexFormat.Uint32,
            frontFace: WGPUFrontFace.CCW,
            cullMode: WGPUCullMode.None
        },
        multisample: {
            count: 1,
            mask: ~0,
            alphaToCoverageEnabled: false
        },
        fragment: &fragmentState,
        depthStencil: null
    };
    
    WGPURenderPipeline pipeline = wgpuDeviceCreateRenderPipeline(gpu.device, &pipelineDesc);
    
    uint mipLevelCount = texture.mipLevels;
    
    WGPUTextureDescriptor mipTextureDesc = {
        size: {
            width: cast(uint)ceil(texture.width / 2.0f),
            height: cast(uint)ceil(texture.height / 2.0f),
            depthOrArrayLayers: 1,
        },
        format: texture.format,
        usage: WGPUTextureUsage.CopySrc | WGPUTextureUsage.TextureBinding | WGPUTextureUsage.RenderAttachment,
        dimension: WGPUTextureDimension.D2,
        mipLevelCount: mipLevelCount - 1,
        sampleCount: 1,
    };
    
    WGPUTexture mipTexture = wgpuDeviceCreateTexture(gpu.device, &mipTextureDesc);
    
    WGPUCommandEncoder cmdEncoder = wgpuDeviceCreateCommandEncoder(gpu.device, null);
    
    WGPUTextureView[] views = new WGPUTextureView[mipLevelCount];
    WGPUBindGroup[] bindGroups = new WGPUBindGroup[mipLevelCount - 1];
    
    //
    
    WGPUTextureViewDescriptor texViewDescriptor0 = {
        label: "src_view",
        aspect: WGPUTextureAspect.All,
        baseMipLevel: 0,
        mipLevelCount: 1,
        dimension: WGPUTextureViewDimension.D2,
        baseArrayLayer: 0,
        arrayLayerCount: 1
    };
    views[0] = wgpuTextureCreateView(texture.texture, &texViewDescriptor0);
    
    foreach (i; 1..mipLevelCount)
    {
        WGPUTextureViewDescriptor texViewDescriptor = {
            label: "dst_view",
            aspect: WGPUTextureAspect.All,
            baseMipLevel: i - 1,
            mipLevelCount: 1,
            dimension: WGPUTextureViewDimension.D2,
            baseArrayLayer: 0,
            arrayLayerCount: 1
        };
        views[i] = wgpuTextureCreateView(mipTexture, &texViewDescriptor);
        assert(views[i] !is null, "Failed to create texture view " ~ i.to!string);
        
        WGPURenderPassColorAttachment colorAttachmentDesc = {
            view: views[i],
            resolveTarget: null,
            loadOp: WGPULoadOp.Clear,
            storeOp: WGPUStoreOp.Store,
            clearValue: WGPUColor(0.0f, 0.0f, 0.0f, 0.0f)
        };
        
        WGPURenderPassDescriptor renderPassDescriptor = {
            colorAttachmentCount: 1,
            colorAttachments: &colorAttachmentDesc,
            depthStencilAttachment: null
        };
        WGPURenderPassEncoder passEncoder = wgpuCommandEncoderBeginRenderPass(cmdEncoder, &renderPassDescriptor);
        
        WGPUBindGroupEntry[2] bgEntries = [
            {
                binding: 0,
                sampler: sampler
            },
            {
                binding: 1,
                textureView: views[i - 1]
            }
        ];
        
        uint bindGroupIndex = i - 1;
        
        WGPUBindGroupDescriptor bgDesc = {
            layout: bindGroupLayout,
            entryCount: cast(uint)bgEntries.length,
            entries: bgEntries.ptr
        };
        
        bindGroups[bindGroupIndex] = wgpuDeviceCreateBindGroup(gpu.device, &bgDesc);
        
        wgpuRenderPassEncoderSetPipeline(passEncoder, pipeline);
        wgpuRenderPassEncoderSetBindGroup(passEncoder, 0, bindGroups[bindGroupIndex], 0, null);
        wgpuRenderPassEncoderDraw(passEncoder, 3, 1, 0, 0);
        wgpuRenderPassEncoderEnd(passEncoder);
    }
    
    WGPUExtent3D mipLevelSize = {
        width: cast(uint)ceil(texture.width / 2.0f),
        height: cast(uint)ceil(texture.height / 2.0f),
        depthOrArrayLayers: 1,
    };
    
    foreach (i; 1..mipLevelCount-1)
    {
        WGPUImageCopyTexture copySource = {
            texture: mipTexture,
            mipLevel: i - 1
        };
        
        WGPUImageCopyTexture copyDestination = {
            texture: texture.texture,
            mipLevel: i
        };
        
        wgpuCommandEncoderCopyTextureToTexture(cmdEncoder, &copySource, &copyDestination, &mipLevelSize);
        mipLevelSize.width  = cast(uint)ceil(mipLevelSize.width / 2.0f);
        mipLevelSize.height = cast(uint)ceil(mipLevelSize.height / 2.0f);
    }
    
    WGPUCommandBuffer commandBuffer = wgpuCommandEncoderFinish(cmdEncoder, null);
    wgpuQueueSubmit(gpu.queue, 1, &commandBuffer);
    wgpuTextureDestroy(mipTexture);
}
