/*
Copyright (c) 2021-2023 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dgpu.asset.texture;

import std.stdio;
import std.conv;
import std.string;
import std.math;
import std.algorithm;
import core.stdc.string: memcpy;
import dlib.core.ownership;
import dlib.core.memory;
import dlib.image.image;
import bindbc.wgpu;
import dgpu.core.gpu;
import dgpu.asset.mipmap;

class Texture: Owner
{
    GPU gpu;
    uint width;
    uint height;
    uint mipLevels;
    uint numLayers;
    WGPUTextureFormat format;
    WGPUTexture texture;
    WGPUTextureView view;
    WGPUSampler sampler;
    string label;
    
    this(GPU gpu, SuperImage[] images, Owner owner)
    {
        super(owner);
        label = toHash.to!string;
        this.gpu = gpu;
        init(images);
        generateMipmap(gpu, this);
    }
    
    this(GPU gpu, SuperImage img, Owner owner)
    {
        this(gpu, [img], owner);
    }
    
    protected void init(SuperImage[] images)
    {
        numLayers = cast(uint)images.length;
        
        this.width = images[0].width;
        this.height = images[0].height;
        
        this.format = WGPUTextureFormat.RGBA8Unorm;
        
        this.mipLevels = cast(uint)log2(max(width, height)) + 1;
        
        WGPUTextureDescriptor textureDescriptor =
        {
            nextInChain: null,
            label: label.toStringz,
            usage: WGPUTextureUsage.TextureBinding | WGPUTextureUsage.CopyDst,
            dimension: WGPUTextureDimension.D2,
            size: WGPUExtent3D(width, height, numLayers),
            format: format,
            mipLevelCount: mipLevels,
            sampleCount: 1
        };
        texture = wgpuDeviceCreateTexture(gpu.device, &textureDescriptor);
        
        WGPUTextureViewDescriptor textureViewDescriptor =
        {
            nextInChain: null,
            label: label.toStringz,
            format: format,
            dimension: WGPUTextureViewDimension.D2Array,
            baseMipLevel: 0,
            mipLevelCount: mipLevels,
            baseArrayLayer: 0,
            arrayLayerCount: numLayers,
            aspect: WGPUTextureAspect.All
        };
        view = wgpuTextureCreateView(texture, &textureViewDescriptor);
        
        foreach(layer, img; images)
        {
            layerFromImage(img, cast(uint)layer);
        }
        
        WGPUSamplerDescriptor samplerDescriptor =
        {
            nextInChain: null,
            label: label.toStringz,
            addressModeU: WGPUAddressMode.Repeat,
            addressModeV: WGPUAddressMode.Repeat,
            addressModeW: WGPUAddressMode.Repeat,
            magFilter: WGPUFilterMode.Linear,
            minFilter: WGPUFilterMode.Linear,
            mipmapFilter: WGPUMipmapFilterMode.Linear,
            lodMinClamp: 0.0f,
            lodMaxClamp: mipLevels,
            compare: WGPUCompareFunction.Undefined,
            maxAnisotropy: 0
        };
        sampler = wgpuDeviceCreateSampler(gpu.device, &samplerDescriptor);
    }
    
    void layerFromImage(SuperImage img, uint layer)
    {
        if (img.channels != 4 || img.bitDepth != 8)
        {
            writeln("Warning: only RGBA8 images are supported");
            return;
        }
        
        if (img.width != width || img.height != height)
        {
            writeln("Warning: image and texture sizes mismatch");
            return;
        }
        
        WGPUBufferDescriptor textureBufferDescriptor = {
            nextInChain: null,
            label: ("TextureBuffer_" ~ label).toStringz,
            usage: WGPUBufferUsage.Storage | WGPUBufferUsage.CopyDst | WGPUBufferUsage.CopySrc,
            size: img.data.length,
            mappedAtCreation: true
        };
        
        WGPUBuffer textureBuffer = wgpuDeviceCreateBuffer(gpu.device, &textureBufferDescriptor);
        void* bufferPtr = wgpuBufferGetMappedRange(textureBuffer, 0, img.data.length);
        memcpy(bufferPtr, img.data.ptr, img.data.length);
        wgpuBufferUnmap(textureBuffer);
        
        WGPUCommandEncoderDescriptor commandEncoderDescriptor = {
            nextInChain: null,
            label: ("CommandEncoder_" ~ label).toStringz,
        };
        WGPUCommandEncoder commandEncoder = wgpuDeviceCreateCommandEncoder(gpu.device, &commandEncoderDescriptor);
        
        WGPUImageCopyBuffer srcCopyBuffer = {
            nextInChain: null,
            layout: {
                nextInChain: null,
                offset: 0,
                bytesPerRow: width * 4,
                rowsPerImage: height
            },
            buffer: textureBuffer
        };
        WGPUImageCopyTexture dstCopyTexture = {
            nextInChain: null,
            texture: texture,
            mipLevel: 0,
            origin: WGPUOrigin3D(0, 0, layer),
            aspect: WGPUTextureAspect.All
        };
        auto copySize = WGPUExtent3D(width, height, 1);
        
        wgpuCommandEncoderCopyBufferToTexture(commandEncoder, &srcCopyBuffer, &dstCopyTexture, &copySize);
        
        WGPUCommandBufferDescriptor commandBufferDescriptor = {
            nextInChain: null,
            label: ("CommandBuffer_" ~ label).toStringz
        };
        WGPUCommandBuffer commandBuffer = wgpuCommandEncoderFinish(commandEncoder, &commandBufferDescriptor);
        wgpuQueueSubmit(gpu.queue, 1, &commandBuffer);
        
        //wgpuCommandEncoderDrop(commandEncoder);
        //wgpuBufferDrop(textureBuffer);
    }
}
