/*
Copyright (c) 2021-2023 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dgpu.render.target;

import bindbc.wgpu;
import dlib.core.ownership;
import dgpu.core.gpu;

struct RenderBuffer
{
    WGPUTextureView view;
    uint width;
    uint height;
}

interface RenderTarget
{
    RenderBuffer nextBackBuffer();
    RenderBuffer depthStencilBuffer();
    WGPUTextureFormat colorFormat();
    WGPUTextureFormat depthStencilFormat();
}

class ScreenRenderTarget: Owner, RenderTarget
{
    GPU gpu;
    WGPUTextureFormat swapChainFormat;
    protected WGPUSwapChain _swapChain;
    protected WGPUTextureView _depthStencilBuffer;
    uint width;
    uint height;
    float aspectRatio;
    
    this(GPU gpu, uint width, uint height, Owner o)
    {
        super(o);
        this.gpu = gpu;
        swapChainFormat = WGPUTextureFormat.BGRA8UnormSrgb; //wgpuSurfaceGetPreferredFormat(gpu.surface, gpu.adapter);
        this.width = width;
        this.height = height;
        this.aspectRatio = cast(float)width / cast(float)height;
        _swapChain = createSwapChain(swapChainFormat, width, height);
        _depthStencilBuffer = createDepthStencilBuffer(width, height);
    }
    
    protected WGPUSwapChain createSwapChain(WGPUTextureFormat format, uint w, uint h) {
        WGPUSwapChainDescriptorExtras swcDescExtras = {
            chain: {
                next: null,
                sType: cast(WGPUSType)WGPUNativeSType.SwapChainDescriptorExtras
            },
            alphaMode: WGPUCompositeAlphaMode.Auto,
            viewFormatCount: 0,
            viewFormats: null
        };
        
        WGPUSwapChainDescriptor swapChainDescriptor = {
            nextInChain: cast(WGPUChainedStruct*)&swcDescExtras,
            usage: WGPUTextureUsage.RenderAttachment,
            format: format,
            width: w,
            height: h,
            presentMode: WGPUPresentMode.Mailbox
        };
        return wgpuDeviceCreateSwapChain(gpu.device, gpu.surface, &swapChainDescriptor);
    }
    
    protected WGPUTextureView createDepthStencilBuffer(uint width, uint height)
    {
        WGPUTextureDescriptor depthTextureDescriptor = {
            nextInChain: null,
            label: "depthTextureDescriptor0",
            usage: WGPUTextureUsage.RenderAttachment,
            dimension: WGPUTextureDimension.D2,
            size: WGPUExtent3D(width, height, 1),
            format: WGPUTextureFormat.Depth24PlusStencil8,
            mipLevelCount: 1,
            sampleCount: 1
        };
        WGPUTexture depthTexture = wgpuDeviceCreateTexture(gpu.device, &depthTextureDescriptor);
        
        WGPUTextureViewDescriptor depthTextureViewDescriptor = {
            nextInChain: null,
            label: "depthTextureViewDescriptor0",
            format: WGPUTextureFormat.Depth24PlusStencil8,
            dimension: WGPUTextureViewDimension.D2,
            baseMipLevel: 0,
            mipLevelCount: 1,
            baseArrayLayer: 0,
            arrayLayerCount: 1,
            aspect: WGPUTextureAspect.All
        };
        WGPUTextureView depthTextureView = wgpuTextureCreateView(depthTexture, &depthTextureViewDescriptor);
        
        return depthTextureView;
    }

    RenderBuffer nextBackBuffer()
    {
        WGPUTextureView nextTexture = wgpuSwapChainGetCurrentTextureView(_swapChain);
        return RenderBuffer(nextTexture, width, height);
    }
    
    RenderBuffer depthStencilBuffer()
    {
        return RenderBuffer(_depthStencilBuffer, width, height);
    }
    
    WGPUTextureFormat colorFormat()
    {
        return swapChainFormat;
    }
    
    WGPUTextureFormat depthStencilFormat()
    {
        return WGPUTextureFormat.Depth24PlusStencil8;
    }
    
    void resize(uint width, uint height)
    {
        this.width = width;
        this.height = height;
        this.aspectRatio = cast(float)width / cast(float)height;
        _swapChain = createSwapChain(swapChainFormat, width, height);
        _depthStencilBuffer = createDepthStencilBuffer(width, height);
    }
    
    void present()
    {
        wgpuSwapChainPresent(_swapChain);
    }
}
