/*
Copyright (c) 2021-2023 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dgpu.render.vertexbuffer;

import core.stdc.string;
import std.string;
import std.conv;
import bindbc.wgpu;
import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dgpu.core.gpu;
import dgpu.asset.entity;
import dgpu.asset.trimesh;
import dgpu.render.renderer;
import dgpu.render.drawable;

struct VertexAttribute
{
    Vector3f v;
    Vector2f t;
    Vector3f n;
}

class VertexBuffer: Drawable
{
    string label;
    
    WGPUBuffer attributeBuffer;
    size_t attributesSize;
    size_t numVertices;
    
    WGPUBuffer indexBuffer;
    size_t indicesSize;
    size_t numIndices;
    
    this(TriangleMesh mesh, Renderer renderer, Owner o)
    {
        super(o);
        label = toHash.to!string;
        
        Vector3f[] vertices = mesh.vertices;
        Vector2f[] texcoords = mesh.texcoords;
        Vector3f[] normals = mesh.normals;
        uint[] indices = mesh.indices;

        numVertices = vertices.length;
        numIndices = indices.length;

        VertexAttribute[] attributes = New!(VertexAttribute[])(numVertices);
        for (size_t i = 0; i < numVertices; i++)
        {
            attributes[i].v = vertices[i];
            attributes[i].t = texcoords[i];
            attributes[i].n = normals[i];
        }

        //uint[] _indices = indices;
        //size_t s = indices.length * uint.sizeof;
        /*
        if (s % 4 != 0) // Should always be aligned to 4 bytes
        {
            _indices = New!(uint[])(indices.length + 1);
            _indices[0..indices.length] = indices[];
        }
        */

        attributesSize = cast(size_t)attributes.length * VertexAttribute.sizeof;
        WGPUBufferDescriptor attributeBufferDescriptor = {
            nextInChain: null,
            label: ("AttributeBuffer_" ~ label).toStringz,
            usage: WGPUBufferUsage.Vertex | WGPUBufferUsage.CopyDst,
            size: attributesSize,
            mappedAtCreation: true
        };
        attributeBuffer = wgpuDeviceCreateBuffer(renderer.gpu.device, &attributeBufferDescriptor);
        void* attributesPtr = wgpuBufferGetMappedRange(attributeBuffer, 0, attributesSize);
        memcpy(attributesPtr, attributes.ptr, attributesSize);
        wgpuBufferUnmap(attributeBuffer);

        indicesSize = cast(size_t)indices.length * uint.sizeof;
        WGPUBufferDescriptor indexBufferDescriptor = {
            nextInChain: null,
            label: ("IndexBuffer_" ~ label).toStringz,
            usage: WGPUBufferUsage.Index | WGPUBufferUsage.CopyDst,
            size: indicesSize,
            mappedAtCreation: true
        };
        indexBuffer = wgpuDeviceCreateBuffer(renderer.gpu.device, &indexBufferDescriptor);
        void* indicesPtr = wgpuBufferGetMappedRange(indexBuffer, 0, indicesSize);
        memcpy(indicesPtr, indices.ptr, indicesSize);
        wgpuBufferUnmap(indexBuffer);

        /*
        if (s % 4 != 0)
        {
            Delete(_indices);
        }
        */

        Delete(attributes);
    }
    
    override void draw(Entity entity, WGPURenderPassEncoder encoder)
    {
        wgpuRenderPassEncoderSetVertexBuffer(encoder, 0, attributeBuffer, 0, WGPU_WHOLE_SIZE);
        wgpuRenderPassEncoderSetIndexBuffer(encoder, indexBuffer, WGPUIndexFormat.Uint32, 0, WGPU_WHOLE_SIZE);
        wgpuRenderPassEncoderDrawIndexed(encoder, cast(uint)numIndices, 1, 0, 0, 0);
    }
}
