/*
Copyright (c) 2020 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module application;

import core.stdc.stdlib;
import std.stdio;
import std.conv;
import bindbc.sdl;
import bindbc.wgpu;
import dlib.core.ownership;
import dlib.core.memory;
import window;
import event;
import time;

void quit(string message = "")
{
    if (message.length)
        writeln(message);
    core.stdc.stdlib.exit(1);
}

static this()
{
    writeln("Initialization...");
    auto sdlSupport = loadSDL();
    writeln("sdlSupport: ", sdlSupport);

    if (sdlSupport == SDLSupport.noLibrary)
        quit("Error: SDL is not installed");

    auto wgpuSupport = loadWGPU();
    writeln("wgpuSupport: ", wgpuSupport);

    if (wgpuSupport == WGPUSupport.noLibrary)
        quit("Error: WGPU is not installed");

    version(OSX)
    {
        SDL_SetHint(SDL_HINT_RENDER_DRIVER, toStringz("metal"));
    }

    if (SDL_Init(SDL_INIT_EVERYTHING) == -1)
        quit("Error: failed to init SDL: " ~ to!string(SDL_GetError()));
    writeln("OK");
}

static ~this()
{
    writeln("Deinitialization...");
    SDL_Quit();
    writeln("OK");
}

class Application: EventListener
{
    protected:
    Window _window;
    Cadencer cadencer;

    public:
    this(uint windowWidth, uint windowHeight, Owner owner = null)
    {
        _window = New!Window(windowWidth, windowHeight, "SDL Application");
        eventManager = New!EventManager(_window.sdlWindow, windowWidth, windowHeight);
        super(eventManager, owner);
        cadencer = New!Cadencer(&onUpdate, 60, this);
    }

    ~this()
    {
        Delete(eventManager);
        Delete(_window);
    }
    
    Window window()
    {
        return _window;
    }
    
    void run()
    {
        Time t = Time(0.0, 0.0);
        
        while(eventManager.running)
        {
            eventManager.update();
            processEvents();
            t.delta = eventManager.deltaTime;
            t.elapsed += t.delta;
            cadencer.update(t);
            onRender();
        }
    }

    void onUpdate(Time t)
    {
        // Override me
    }
    
    void onRender()
    {
        // Override me
    }
}
