/*
Copyright (c) 2020 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module texture;

import core.stdc.string;
import std.stdio;
import bindbc.wgpu;
import dlib.core.memory;
import dlib.core.ownership;
import dlib.image.image;

// TODO: support more image formats 
class Texture: Owner
{
    WGPUDeviceId device;
    WGPUQueueId queue;
    
    WGPUTextureId id;
    WGPUTextureViewId viewId;
    
    uint width;
    uint height;
    
    this(WGPUDeviceId device, WGPUQueueId queue, uint width, uint height, uint numLayers, Owner owner)
    {
        super(owner);
        
        this.device = device;
        this.queue = queue;
        
        this.width = width;
        this.height = height;
        
        WGPUTextureDescriptor textureDescriptor =
        {
            size: WGPUExtent3d(width, height, 1),
            array_layer_count: numLayers,
            mip_level_count: 1,
            sample_count: 1,
            dimension: WGPUTextureDimension.D2,
            format: WGPUTextureFormat.Rgba8Unorm,
            usage: WGPUTextureUsage_SAMPLED | WGPUTextureUsage_COPY_DST
        };
        id = wgpu_device_create_texture(device, &textureDescriptor);

        WGPUTextureViewDescriptor textureViewDescriptor =
        {
            format: WGPUTextureFormat.Rgba8Unorm,
            dimension: WGPUTextureViewDimension.D2Array,
            aspect: WGPUTextureAspect.All,
            base_mip_level: 0,
            level_count: 1,
            base_array_layer: 0,
            array_layer_count: numLayers
        };
        viewId = wgpu_texture_create_view(id, &textureViewDescriptor);
    }
    
    void layerFromImage(SuperImage img, uint layer)
    {
        if (img.channels != 4 || img.bitDepth != 8)
        {
            writeln("Warning: only RGBA8 images are supported");
            return;
        }
        
        if (img.width != width || img.height != height)
        {
            writeln("Warning: image and texture sizes mismatch");
            return;
        }
        
        WGPUBufferDescriptor texBufferDescriptor = WGPUBufferDescriptor(img.data.length,
            WGPUBufferUsage_STORAGE | WGPUBufferUsage_MAP_READ | WGPUBufferUsage_MAP_WRITE | WGPUBufferUsage_COPY_SRC);
        ubyte* texBufferMem;
        WGPUBufferId textureBuffer = wgpu_device_create_buffer_mapped(device, &texBufferDescriptor, &texBufferMem);
        memcpy(texBufferMem, img.data.ptr, img.data.length);
        wgpu_buffer_unmap(textureBuffer);
       
        WGPUCommandEncoderDescriptor texCopyDescriptor = WGPUCommandEncoderDescriptor(0);
        WGPUCommandEncoderId texCopyCmdEncoder = wgpu_device_create_command_encoder(device, &texCopyDescriptor);
        
        WGPUBufferCopyView srcBufferCopyView =
        {
            buffer: textureBuffer,
            offset: 0,
            row_pitch: width * 4,
            image_height: height
        };
        
        WGPUTextureCopyView dstTextureCopyView =
        {
            texture: id,
            mip_level: 0,
            array_layer: layer,
            origin: WGPUOrigin3d(0, 0, 0)
        };
        
        wgpu_command_encoder_copy_buffer_to_texture(texCopyCmdEncoder, &srcBufferCopyView, &dstTextureCopyView, WGPUExtent3d(width, height, 1));
        WGPUCommandBufferId texCopyCmdBuf = wgpu_command_encoder_finish(texCopyCmdEncoder, null);
        wgpu_queue_submit(queue, &texCopyCmdBuf, 1);
    }
}
