/*
Copyright (c) 2020 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module window;

import std.stdio;
import std.conv;
import std.string;
import bindbc.sdl;

class Window
{
    protected:
    SDL_Window* _sdlWindow = null;
    SDL_SysWMinfo _wmInfo;
    uint _width = 800;
    uint _height = 600;
    bool _fullscreen = false;

    public:
    this(uint width, uint height, string title)
    {
        _width = width;
        _height = height;
        init(title);
    }

    protected void init(string title)
    {
        _sdlWindow = SDL_CreateWindow(toStringz(title),
           SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
           _width, _height,
           SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE);

        if (_sdlWindow)
        {
            SDL_GetWindowWMInfo(_sdlWindow, &_wmInfo);
        }
    }

    protected void destroy()
    {
        if (_sdlWindow)
            SDL_DestroyWindow(_sdlWindow);
    }

    SDL_Window* sdlWindow()
    {
        return _sdlWindow;
    }

    SDL_SysWMinfo wmInfo()
    {
        return _wmInfo;
    }

    uint width()
    {
        return _width;
    }

    uint height()
    {
        return _height;
    }

    bool fullscreen()
    {
        return fullscreen;
    }

    void setFullscreen(bool mode, bool changeResolution = true)
    {
        if (_sdlWindow)
        {
            uint flags = 0;
            if (mode)
            {
                if (changeResolution)
                    flags |= SDL_WINDOW_FULLSCREEN;
                else
                    flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
            }

            SDL_SetWindowFullscreen(_sdlWindow, flags);
            querySize();

            _fullscreen = mode;
        }
    }

    protected void querySize()
    {
        int w = _width;
        int h = _height;
        SDL_GetWindowSize(sdlWindow, &w, &h);
        _width = cast(uint)w;
        _height = cast(uint)h;
    }

    void maximize()
    {
        if (_sdlWindow)
        {
            SDL_MaximizeWindow(_sdlWindow);
            querySize();
        }
    }

    void minimize()
    {
        if (_sdlWindow)
            SDL_MinimizeWindow(_sdlWindow);
    }
}
